import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { AnimatedNoise } from "@/components/ui/AnimatedNoise";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "DataWatt Lyon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className="bg-gray-200">
        <div className=' fixed h-screen w-full overflow-hidden -z-10'>
          <AnimatedNoise opacity={0.07}/>
        </div>
        <Navbar />
          {children}
        <Footer />
      </body>
    </html>
  );
}
